import { useWeb3React } from '@web3-react/core'
import Head from 'next/head'
import Home from './home'

export default function Index() {
  const { account } = useWeb3React()
  console.log(account)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </>
  )
}
